name: Check style

on: push

jobs:
  build:
    needs: deps
    name: Check style
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm ci 
    - name: Run ESLint
      run: npm run lint