name: Build & publish

on:
  push:
    branches:
      - main

jobs:
  renderer:
    needs: deps
    runs-on: ubuntu-latest
    steps:
      - run: npm run build:renderer
  publish:
    needs: renderer
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Publish releases
        env:
          # These values are used for auto updates signing
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EP_PRE_RELEASE: true
        run: |
          npm run postinstall
          npm run build
          npm exec electron-builder --publish always
